### ISSUE TITLE
roboto should not be a dependency

### ISSUE THREAD

**Issue by renfeng** [googlecast/cast-video-polymer#1]

**Comment by pengying** [comment]
You mean as the default font of the element?

**Comment by renfeng** [comment]
Perhaps... roboto was referenced indirectly by cast-video

cast-video.html
```
<link rel="import" href="../cast-theme-polymer/cast-theme.html">
```

cast-theme.html
```
<link rel="import" href="../font-roboto/roboto.html">
```

**Comment by pengying** [comment]
It's the font dependency.

**Comment by renfeng** [comment]
Yes. I know it's font dependency... Since the very first quick start guide, it's recommended to remove/comment out the dependency on roboto to make page load faster. Not everyone has a fast internet connection to download roboto... e.g. I have a fast connection to YouTube, but not to googleapis.com. I don't know why. But, that's a fact.

**Comment by pengying** [comment]
Have you taken a look at [vulcanize](https://github.com/polymer/vulcanize)/[polybuild](https://github.com/PolymerLabs/polybuild).  By including it as a dependency you can inline it into a single page request.  It's actually quite fast.
